services:
  backend:
    build:
      context: ./backend      # Points to the backend folder
      dockerfile: Dockerfile    
    container_name: backend_app
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend     # Points to the frontend folder
      dockerfile: Dockerfile   
    container_name: frontend_app
    ports:
      - "3000:3000"           